### ISSUE TITLE
Add unit-test

### ISSUE THREAD

**Issue by PatelUtkarsh** [rtCamp/wp-google-login#16]
- [x] phpunit
- [x] Integrate phpunit using GitHub Action

**Comment by deepaklalwani97** [comment]
@DevikVekariya The rtBot review can be dismissed as it is a false flag and the PR looks good to me and i have tested the test cases on my local all are passing.

**Comment by DevikVekariya** [comment]
@mrrobot47 is working for GH actions setup here and expecting 3 hours of sys work

**Comment by deepaklalwani97** [comment]
@DevikVekariya I have fixed the missing code coverage which I could fix and added code-coverage ignore on lines which could not be tested with proper comments with reason.

**Comment by DevikVekariya** [comment]
@deepaklalwani97 I see there are many code coverage ignore blocks without comment! Please add a proper comment on that

**Comment by deepaklalwani97** [comment]
@DevikVekariya Added comment/fixed ignore blocks

**Comment by deepaklalwani97** [comment]
Merged #19 to  develop while testing develop branch  on https://deepak.dev4.rt.gw/ found an issue with redirection after successful login the site redirects to http://httpsdeepak.dev4.rt.gwwp-admin1/

**Comment by deepaklalwani97** [comment]
@pooja-muchandikar Can you test the develop branch for this repo on https://deepak.dev4.rt.gw/. I have added the latest develop zip in this site and configured it with secrets. I have also added your user to the site. Let me know if you face any issues.
CC: @DevikVekariya

**Comment by pooja-muchandikar** [comment]
@deepaklalwani97 

I have tested the site with google login and works as expected with my below findings.

- ( with already existing user on site ) tried google login and was able to login successfully :heavy_check_mark: 

- Tried google login on the site with email other than rtcamp email and login was blocked as expected :heavy_check_mark: 

- Deleted user from the site and enabled `anyone can register` option and tried to login and was able to login successfully and subscriber role got assigned :heavy_check_mark:

**Comment by deepaklalwani97** [comment]
@DevikVekariya Created PR  to master branch as the develop branch has been tested. #26

**Comment by DevikVekariya** [comment]
@deepaklalwani97 I see lots of errors from bot here https://github.com/rtCamp/wp-google-login/issues/16

**Comment by deepaklalwani97** [comment]
@DevikVekariya We can ignore these errors. All these errors are from unit tests we have ignored tests folder in `phpcs.xml`  but seem like bot does not respect `phpcs.xml` file

**Comment by DevikVekariya** [comment]
@deepaklalwani97 debug why phpcs is not being ignored from test!

I'll be able to merge only when all checks are being passed. Can't ignore it in this way.

**Comment by DevikVekariya** [comment]
All seems clear to release this. 

Will do merge this PR https://github.com/rtCamp/wp-google-login/pull/29 and release it tomorrow morning.

cc @sagarnasit
