### ISSUE TITLE
mu-plugins support

### ISSUE THREAD

**Issue by rahul286** [rtCamp/wp-google-login#18]
Please test the plugin if it works as a `mu-plugins`.

**Comment by deepaklalwani97** [comment]
@DevikVekariya I have tested the plugin as mu-plugin and it works fine.

**Comment by DevikVekariya** [comment]
It seems all working as expected.

@sagarnasit We can add this in the readme that this plugin works with `mu-plugins` too.

**Comment by DevikVekariya** [comment]
Added in Readme. Closing this issue
